# Generated by Django 3.0.8 on 2020-07-05 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country_code',
        ),
    ]
